name: wavy_muic_player
description: "A muic player with stuning wave like ui"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  curved_navigation_bar: ^1.0.6
  permission_handler: ^12.0.1
  path_provider: ^2.1.0
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_waveforms: ^2.0.1
  provider: ^6.1.5+1
  audio_metadata_reader: ^1.4.2
  objectbox: ^2.0.0
  audiotags: ^1.4.5
  objectbox_flutter_libs: ^2.5.1
  audio_session: ^0.1.25
  flutter_native_splash: 2.4.7
  carousel_slider: ^5.1.1

launcher_name:
  default: "Wavy"


flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/icon/wavy_icon.png"

  image_path_android: "assets/icon/wavy_icon.png"
  adaptive_icon_background: "assets/icon/wavy_icon_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/wavy_icon_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icon/wavy_icon_adaptable.png" # only available for Android 13 devices and above

  image_path_ios: "assets/icon/wavy_icon.png"
  image_path_ios_dark_transparent: "assets/icon/wavy_icon_transparent.png"
  image_path_ios_tinted_grayscale: "assets/icon/wavy_icon_monochrome.png"
  desaturate_tinted_to_grayscale_ios: true
  # background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icon/wavy_icon.png"
    background_color: "#ffffff"
  macos:
    generate: true
    image_path: "assets/icon/wavy_icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/wavy_icon.png"
    background_color: "#ffffff"

flutter_native_splash:
  android: true
  ios: true
  web: false

  image: "assets/icon/wavy_splash_image.png"
  color: "#FFE695"

  image_dark: "assets/icon/wavy_splash_image.png"
  color_dark: "#342E1B"

  android_12:
    image: "assets/icon/wavy_splash_image.png"
    color: "#FFE695"

    image_dark: "assets/icon/wavy_splash_image.png"
    color_dark: "#342E1B"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  objectbox_generator: ^2.0.0
  change_app_package_name: 1.4.0
  launcher_name: 1.0.2
  flutter_launcher_icons: 0.14.1


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/default_placeholder_image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
